test-server:
  only:
    - merge_requests
  image: python:3.9.13-slim-buster
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    PYTHONPATH: "./server:./server/src"
    POSTGRES_USER: searchwing
    POSTGRES_PASSWORD: searchwing
    POSTGRES_DB: searchwing
    POSTGRES_SERVER: db
    POSTGRES_PORT: 5432
    POSTGRES_TEST_PORT: 5432
    POSTGRES_TEST_SERVER: test-db
  tags:
    - flight-log
  services:
    - name: postgis/postgis:14-3.3
      alias: test-db
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
  - apt update -y && apt install make -y
  - apt-get update && apt-get -y install libpq-dev gcc
  - make --version
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - make install-back-deps
  - make install-back-test-deps
  script:
  - make lint-server
  - make test-server
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

deploy-dev:
  only:
    - dev
  stage: build
  tags:
    - flight-log
  variables:
    BACKEND_IMAGE_TAG: $CI_REGISTRY_IMAGE/server:$CI_COMMIT_REF_SLUG
    DOCKER_TLS_CERTDIR: "/certs"
  environment: staging
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo $CI_REGISTRY_IMAGE
    - echo $CI_COMMIT_REF_SLUG
    - echo $BACKEND_IMAGE_TAG
  script:
    - echo "Building"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $BACKEND_IMAGE_TAG ./server
    - docker push $BACKEND_IMAGE_TAG
    - echo "Deploying backend on CapRover..."
    - docker run caprover/cli-caprover:latest caprover deploy --caproverUrl $CAPROVER_URL --appToken $CAPROVER_BACKEND_APP_TOKEN --caproverApp $CAPROVER_BACKEND_APP --imageName $BACKEND_IMAGE_TAG

deploy:
  only:
    - main
  stage: deploy
  script: echo "TBD!"
  environment: production
