version: "3.3"

services:
  server:
    container_name: api
    build:
      context: server
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080 --log-level info
    volumes:
      - ./server:/app
      - ./storage:/app/storage/
    ports:
      - "8080:8080"
    depends_on:
      - db
      - migrations
    environment:
      POSTGRES_USER: searchwing
      POSTGRES_PASSWORD: searchwing
      POSTGRES_DB: searchwing
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432

  db:
    container_name: db
    build:
      context: server
      dockerfile: Dockerfile.db
    restart: always
    environment:
      POSTGRES_USER: searchwing
      POSTGRES_PASSWORD: searchwing
      POSTGRES_DB: searchwing
    ports:
      - "5432:5432"
    volumes:
      - ./server/db:/docker-entrypoint-initdb.d/

  migrations:
    container_name: migrations
    build:
      context: server
    command: alembic upgrade head
    volumes:
      - ./server:/app
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      POSTGRES_USER: searchwing
      POSTGRES_PASSWORD: searchwing
      POSTGRES_DB: searchwing
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

volumes:
  storage:
